### ISSUE TITLE
The request has both SAS authentication scheme and 'Bearer' authorization scheme. Only one scheme should be used.

### ISSUE THREAD

**Issue by gwinnem** [Azure/apim-lab#106]
Describe the bug

After following JSON Web Token Validation at 
https://azure.github.io/apim-lab/apim-lab/7-security/apimanagement-7-1-JWT-Validation.html 
I get this response:

The request has both SAS authentication scheme and 'Bearer' authorization scheme. Only one scheme should be used

To Reproduce
Follow the above lab excersize: Azure Apim Hands On Lab

Expected behavior
Http Status code 200 returned but im getting the 401

**Comment by Chad-Dumas-MSFT** [comment]
I've ran the lab twice without issue.  @gwinnem, can you attempt again by copy/paste the payload, enter secret:  123412341234123412341234 in Verify Signature and check 'secret base64 encoded'.  From there, copy and paste the inbound policy as shared and run it again?  Thanks.

**Comment by gwinnem** [comment]
Tnxs for the reply.
I will try again later today and get back to you.

**Comment by gwinnem** [comment]
@Chad-Dumas-MSFT 
The issue was caused by the logic app, and i solved it by adding:
<set-header name="Authorization" exists-action="delete" />
To the inbound policy. So my config resulted in:

<policies>
    <inbound>
        <validate-jwt header-name="Authorization" failed-validation-httpcode="401" failed-validation-error-message="Unauthorized" require-expiration-time="true" require-scheme="Bearer" require-signed-tokens="true" clock-skew="10">
            <issuer-signing-keys>
                <key>123412341234123412341234</key>
            </issuer-signing-keys>
            <issuers>
                <issuer>Ringana</issuer>
            </issuers>
        </validate-jwt>
        <set-header name="Authorization" exists-action="delete" />
    </inbound>
    <backend>
        <forward-request />
    </backend>
    <outbound />
    <on-error />
</policies>
