### ISSUE TITLE
Typo and Suggestion in Developer Portal -> Publishing Developer Portal

### ISSUE THREAD

**Issue by asofio** [Azure/apim-lab#28]
The first sentence in the second paragraph reads:

_Once you have accessed the dev portal in admin mode. Now, we can proceed with its publishing for anonymous and **authenticaded** roles._

Suggested change:

_After having accessed the dev portal in admin mode, you can now proceed with publishing to allow for anonymous and **authenticated** roles._

**Comment by simonkurtz-MSFT** [comment]
Thank you, @asofio! This has recently been rewritten to 

_You can now proceed with publishing the Developer Portal to allow anonymous and authenticated roles._
