### ISSUE TITLE
Add more detail on why (context.User.Id) is not getting evaluated from Azure management portal under Transformation policies

### ISSUE THREAD

**Issue by anu-01** [Azure/apim-lab#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asofio** [comment]
Along with a clearer explanation, would it be helpful to change the code to what is shown below so that this does not cause a failure?

`<value>@(context.User == null ? "Unknown" : context.User.Id)</value>`

**Comment by simonkurtz-MSFT** [comment]
This was removed from the lab as it was problematic and seemingly did not illustrate the value of transformation policies any more than what we already have in place.
