### ISSUE TITLE
Typo in Adding APIs -> Calling APIs

### ISSUE THREAD

**Issue by asofio** [Azure/apim-lab#30]
Documentation reads:

_Here we will **se** this form, where we can add the domain name of our frontend_

Should read:

_Here we will **see** this form, where we can add the domain name of our frontend_

**Comment by simonkurtz-MSFT** [comment]
Thank you, @asofio! This has recently been corrected, so I will close out this issue.

![image](https://user-images.githubusercontent.com/84809797/151244268-7819ae06-d07f-4f77-a519-038bb8e2f25c.png)
