### ISSUE TITLE
Policy Expressions->Transformational Policies->Amend what’s passed to the backend - Tracing location incorrect

### ISSUE THREAD

**Issue by RussSmi** [Azure/apim-lab#31]
Policy Expressions->Transformational Policies->Amend what’s passed to the backend

This section mentions viewing the Trace in the developer portal, I saw this note:

"Note - this trace below was from the Developer portal. I got errors when testing from the Azure Management portal, as the [User Id] is unable to be evaluated."

I then spent some time trying to find out how to view the Trace in the developer portal and then had to ask for help.  I think viewing tracing in the developer portal was mentioned in an earlier exercise too.  I asked for help and it was explained that basically you can't with a regular user.  Could the content be updated to show how to view the trace correctly in this exercise.

**Comment by simonkurtz-MSFT** [comment]
Hi @RussSmi, this section was recently rewritten. Could you recheck and close this out, if no longer needed, please?

https://azure.github.io/apim-lab/apim-lab/4-policyExpressions/apimanagement-4-3-Transformation.html#amend-whats-passed-to-the-backend

**Comment by RussSmi** [comment]
Yes this can be closed, looks like the trace part has been removed
