### ISSUE TITLE
Log-to-eventhub section would be clearer with addition of one step

### ISSUE THREAD

**Issue by asanjabi** [Azure/apim-lab#34]
**Describe the bug**
at: [https://azure.github.io/apim-lab/apim-lab/6-analyticsMonitoring/apimanagement-6-3-EventHub.html#configure-log-to-eventhub-policies](https://azure.github.io/apim-lab/apim-lab/6-analyticsMonitoring/apimanagement-6-3-EventHub.html#configure-log-to-eventhub-policies)
Between step 5 and 6 it would be clearer if there was another step to open **policy code editor**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by simonkurtz-MSFT** [comment]
Hi @asanjabi, the steps in this lab were recently updated, and we know mentioned to enter the Code editor in step 6. Could you please review the documentation to see if it's suitable now? Thank you!

**Comment by simonkurtz-MSFT** [comment]
Closing this issue due to lack of response and recent overhauls of the steps.
