### ISSUE TITLE
Calculator API CORS Issue in Developer Portal Due to Incorrect Protocol for APIM

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [Azure/apim-lab#41]
**Describe the bug**

The screenshot in the documentation on importing the Calculator API [shows to set the _URL scheme_ to `HTTP`](https://azure.github.io/apim-lab/apim-lab/3-addingApis/apimanagement-3-2.html). While testing from _within_ APIM itself works and returns a proper `200`, using the Developer Portal fails with a CORS issue. Specifically, it's failing due to a `mixed-content` violation. The Developer Portal itself runs on `HTTPS` and is attempting to make a call to APIM but fails due to APIM only accepting `HTTP`. 

**To Reproduce**
1. Set up the Calculator API as described [here](https://azure.github.io/apim-lab/apim-lab/3-addingApis/apimanagement-3-2.html).
1. Go to the Developer Portal and try to make a request to the Calculator API.
1. Note the CORS error in the response. 
1. Open the brower's developer tools and observe the mixed-content error on the network tab.

**Expected behavior**
The request should be allowed, and a `200` should be returned along with a response body showing the result.

**Comment by simonkurtz-MSFT** [comment]
@ferantoMSFT, I am going to address this in a PR and will link to this issue.

**Comment by simonkurtz-MSFT** [comment]
The only reference to `http` is in the `basePath` property in the [OpenAPI json](http://calcapi.cloudapp.net/calcapi.json). There is no reference to `https` since the backend does not implement https. I suspect the OpenAPI import in APIM makes some assertion on what scheme to use as, by contrast, importing the [Petstore API](https://petstore.swagger.io/v2/swagger.json) sets the scheme to `Both`.

Using `basePath` for the backend URL makes sense to me, but I'm not sure we should do that on the APIM ingress as we want to encourage customers to use HTTPS throughout. Would it make more sense to at least set `Both`, if not `HTTPS`, when the import detects HTTP-only? This would also avoid CORS issues.

This may be a question for @mikebudzynski.

**Comment by mikebudzynski** [comment]
@simonkurtz-MSFT I don't have much context here, but the developer portal requires either:

1. Configuring CORS policy on the APIs, or
2. Enabling the CORS proxy feature

Both options are covered here: https://docs.microsoft.com/en-us/azure/api-management/developer-portal-faq#cors

**Comment by simonkurtz-MSFT** [comment]
Hi @mikebudzynski, CORS is set up, but I don't see it as the root cause here. When the _swagger.json_ import occurs, APIM appears to make a decision on what protocols to allow that has a detrimental effect here. If the API definition only has `http`, as is the case in the _CalcAPI_, APIM correctly sets the backend protocol to `http`, but I think it should set the frontend to `Both` as that would future-proof it, provided a cert is available for the APIM URL. `azure-api.net` would be on `https`, and APIM could check whether any and all custom domains that may be used to access the _CalcAPI_, can also run `https`.

**Comment by simonkurtz-MSFT** [comment]
I mitigated this issue via our APIM Lab documentation, and I am comfortable closing it out at this time; however, the root cause continues to exist.
