### ISSUE TITLE
link giving 404 error

### ISSUE THREAD

**Issue by x21128332** [Azure/apim-lab#82]
In Prerequisites nindex.md the links for deploying your own API is giving 404 error

apim-lab/0-labPrerequisites/index.md

**To Reproduce**
1. Go to 'apim-lab/0-labPrerequisites/index.md'
2. Scroll down to 'in case this website is down you can deploy your own API using the following instructions'
3. Click on 'instructions'
5. See error

**Comment by ferantoMSFT** [comment]
Thanks for bringing this up @x21128332 ! Link has been fixed, although the underlying instructions might be a little bit outdated. If you can try those would be great!
